"""initial schema

Revision ID: b4b98a667a5d
Revises: 
Create Date: 2026-06-19 05:13:56.417949
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b4b98a667a5d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('smiles', sa.Text(), nullable=False),
    sa.Column('inchikey', sa.String(length=27), nullable=True),
    sa.Column('source_organism', sa.String(length=512), nullable=True),
    sa.Column('source_db', sa.String(length=64), nullable=False),
    sa.Column('coconut_id', sa.String(length=64), nullable=True),
    sa.Column('molecular_descriptors', sa.JSON(), nullable=False),
    sa.Column('references', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coconut_id')
    )
    op.create_index(op.f('ix_compounds_inchikey'), 'compounds', ['inchikey'], unique=False)
    op.create_index(op.f('ix_compounds_name'), 'compounds', ['name'], unique=False)
    op.create_table('neoantigens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tumor_type', sa.String(length=128), nullable=False),
    sa.Column('peptide', sa.String(length=64), nullable=False),
    sa.Column('mhc_allele', sa.String(length=64), nullable=False),
    sa.Column('binding_score', sa.Float(), nullable=True),
    sa.Column('presentation_rank', sa.Float(), nullable=True),
    sa.Column('structure_uri', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_neoantigens_tumor_type'), 'neoantigens', ['tumor_type'], unique=False)
    op.create_table('targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('protein', 'neoantigen', name='targettype'), nullable=False),
    sa.Column('pdb_id', sa.String(length=16), nullable=True),
    sa.Column('gene', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('dockable', sa.Boolean(), nullable=False),
    sa.Column('box_center_x', sa.Float(), nullable=True),
    sa.Column('box_center_y', sa.Float(), nullable=True),
    sa.Column('box_center_z', sa.Float(), nullable=True),
    sa.Column('box_size_x', sa.Float(), nullable=True),
    sa.Column('box_size_y', sa.Float(), nullable=True),
    sa.Column('box_size_z', sa.Float(), nullable=True),
    sa.Column('box_source', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_targets_gene'), 'targets', ['gene'], unique=False)
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('compound_set', sa.JSON(), nullable=False),
    sa.Column('weights', sa.JSON(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('created', 'queued', 'running', 'completed', 'failed', name='experimentstatus'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lab_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compound_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('measured_ic50', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=256), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['compound_id'], ['compounds.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_results_compound_id'), 'lab_results', ['compound_id'], unique=False)
    op.create_table('docking_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('compound_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('binding_affinity', sa.Float(), nullable=False),
    sa.Column('pose_uri', sa.Text(), nullable=True),
    sa.Column('box_used', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['compound_id'], ['compounds.id'], ),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_docking_results_compound_id'), 'docking_results', ['compound_id'], unique=False)
    op.create_index(op.f('ix_docking_results_experiment_id'), 'docking_results', ['experiment_id'], unique=False)
    op.create_table('effectiveness_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('compound_id', sa.Integer(), nullable=False),
    sa.Column('binding_score', sa.Float(), nullable=True),
    sa.Column('neoantigen_score', sa.Float(), nullable=True),
    sa.Column('response_score', sa.Float(), nullable=True),
    sa.Column('simulation_score', sa.Float(), nullable=True),
    sa.Column('combined_score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['compound_id'], ['compounds.id'], ),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_effectiveness_scores_compound_id'), 'effectiveness_scores', ['compound_id'], unique=False)
    op.create_index(op.f('ix_effectiveness_scores_experiment_id'), 'effectiveness_scores', ['experiment_id'], unique=False)
    op.create_table('response_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('compound_id', sa.Integer(), nullable=False),
    sa.Column('cell_line', sa.String(length=128), nullable=False),
    sa.Column('predicted_ic50', sa.Float(), nullable=False),
    sa.Column('applicability_in_domain', sa.Boolean(), nullable=False),
    sa.Column('nn_tanimoto', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['compound_id'], ['compounds.id'], ),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_response_predictions_compound_id'), 'response_predictions', ['compound_id'], unique=False)
    op.create_index(op.f('ix_response_predictions_experiment_id'), 'response_predictions', ['experiment_id'], unique=False)
    op.create_table('simulation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('compound_id', sa.Integer(), nullable=False),
    sa.Column('baseline_population', sa.Integer(), nullable=False),
    sa.Column('final_population', sa.Integer(), nullable=False),
    sa.Column('reduction_pct', sa.Float(), nullable=False),
    sa.Column('frames_uri', sa.Text(), nullable=True),
    sa.Column('illustrative_notice', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['compound_id'], ['compounds.id'], ),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_runs_compound_id'), 'simulation_runs', ['compound_id'], unique=False)
    op.create_index(op.f('ix_simulation_runs_experiment_id'), 'simulation_runs', ['experiment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulation_runs_experiment_id'), table_name='simulation_runs')
    op.drop_index(op.f('ix_simulation_runs_compound_id'), table_name='simulation_runs')
    op.drop_table('simulation_runs')
    op.drop_index(op.f('ix_response_predictions_experiment_id'), table_name='response_predictions')
    op.drop_index(op.f('ix_response_predictions_compound_id'), table_name='response_predictions')
    op.drop_table('response_predictions')
    op.drop_index(op.f('ix_effectiveness_scores_experiment_id'), table_name='effectiveness_scores')
    op.drop_index(op.f('ix_effectiveness_scores_compound_id'), table_name='effectiveness_scores')
    op.drop_table('effectiveness_scores')
    op.drop_index(op.f('ix_docking_results_experiment_id'), table_name='docking_results')
    op.drop_index(op.f('ix_docking_results_compound_id'), table_name='docking_results')
    op.drop_table('docking_results')
    op.drop_index(op.f('ix_lab_results_compound_id'), table_name='lab_results')
    op.drop_table('lab_results')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_targets_gene'), table_name='targets')
    op.drop_table('targets')
    op.drop_index(op.f('ix_neoantigens_tumor_type'), table_name='neoantigens')
    op.drop_table('neoantigens')
    op.drop_index(op.f('ix_compounds_name'), table_name='compounds')
    op.drop_index(op.f('ix_compounds_inchikey'), table_name='compounds')
    op.drop_table('compounds')
    # ### end Alembic commands ###
