"""Single source of truth for the two load-bearing safety notices.

NaturaScreen makes two distinct honesty claims, and they are easy to conflate:

1. ``DISCLAIMER`` — the *cure* boundary. Every result and export is a research
   hypothesis, never a treatment, cure, dose, or medical recommendation.

2. ``SIMULATION_NOTICE`` — the *illustration* boundary. The agent-based tumor
   simulation is a qualitative illustration of the effectiveness score, not a
   prediction of tumor response. The growth/shrinkage rate on screen is produced by
   a heuristic transfer function from the compound's scores; there is no validated
   function mapping a binding score (kcal/mol) or predicted IC50 to a tumor growth
   rate. A smooth, authoritative-looking animation is the exact place a desperate
   reader is misled, so this notice is treated as load-bearing as the cure
   disclaimer and is enforced through the type system (see ``schemas``).

These constants are imported wherever a payload must carry a notice. Do not inline
the text elsewhere; import it so there is exactly one wording to audit.
"""

from __future__ import annotations

DISCLAIMER: str = (
    "NaturaScreen produces research hypotheses for laboratory investigation only. "
    "Nothing here is a verified cancer treatment, cure, dose, or medical "
    "recommendation. Predicted effects are not validated for human use. Any candidate "
    "requires cell-culture work, animal studies, and human clinical trials before it "
    "could be considered a treatment. If you or someone you know has cancer, consult a "
    "qualified clinician; do not act on anything in this tool."
)

SIMULATION_NOTICE: str = (
    "Illustrative, not predicted. This simulation is a qualitative illustration of the "
    "effectiveness score, not a prediction of tumor response. The shrinkage rate shown "
    "is generated by a heuristic transfer function from the compound's scores, not a "
    "validated model of how this compound affects any real tumor or patient."
)

# Shown on the response sub-score when a compound falls outside the model's
# applicability domain (trained on synthetic-drug data; out-of-distribution for most
# natural products). See services/response.
RESPONSE_OOD_NOTICE: str = (
    "Out-of-distribution: the response model is trained on synthetic-drug screens "
    "(GDSC) and this natural compound is dissimilar to its training set. This "
    "prediction is low-confidence and should be treated as a weak signal at most."
)
